[firebase]
type = "service_account"
project_id = "nama-proyek-firebase-anda"
private_key_id = "xxxxxxxxx"
private_key = """-----BEGIN PRIVATE KEY-----
... kunci privat Anda ...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-...@...gserviceaccount.com"
client_id = "xxxxxxxx"
auth_uri = "https://accounts.google.com/o/zoom/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/..."
universe_domain = "googleapis.com"